# Generated by Django 4.2.1 on 2023-05-31 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotDataBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PhotoURL', models.URLField()),
                ('Name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('tel', models.CharField(max_length=200)),
                ('work_schedule', models.CharField(max_length=200)),
                ('SiteURL', models.URLField()),
            ],
        ),
    ]
