# Generated by Django 4.2.1 on 2023-07-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminkaBot', '0002_alter_botdatabase_options_botdatabase_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botdatabase',
            name='Photo',
            field=models.ImageField(default='', upload_to='photo/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='botdatabase',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=250, verbose_name='e-mail'),
        ),
        migrations.AddField(
            model_name='botdatabase',
            name='town',
            field=models.CharField(default='Теребовля', max_length=200, verbose_name='Місто'),
        ),
        migrations.AlterField(
            model_name='botdatabase',
            name='FaсebookURL',
            field=models.URLField(blank=True, default='', max_length=300, verbose_name='Фейсбук'),
        ),
        migrations.AlterField(
            model_name='botdatabase',
            name='InstagramURL',
            field=models.URLField(blank=True, default='', max_length=300, verbose_name='Інстаграм'),
        ),
        migrations.AlterField(
            model_name='botdatabase',
            name='SiteURL',
            field=models.URLField(blank=True, max_length=300, verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='botdatabase',
            name='category',
            field=models.CharField(choices=[('ГоловаГромади', 'ГоловаГромади'), ('ЗаступникиГолови', 'ЗаступникиГолови'), ('Старости', 'Старости'), ('Відділи', 'Відділи'), ('Ательє', 'Ательє'), ('Кафе', 'Кафе'), ('Клуби', 'Клуби'), ('Ресторани', 'Ресторани'), ('Фастфуди', 'Фастфуди'), ('Піцерії', 'Піцерії'), ('Спортзали', 'Спортзали'), ('Банки', 'Банки'), ('Казначейство', 'Казначейство'), ('КредитніСпілки', 'КредитніСпілки'), ('РемонтАвто', 'РемонтАвто'), ('РемонтТехніки', 'РемонтТехніки'), ('Нотаріуси', 'Нотаріуси'), ('ДитячеДозвілля', 'ДитячеДозвілля'), ('Заправки', 'Заправки'), ('Доставка', 'Доставка'), ('МагПродуктові', 'МагПродуктові'), ('МагДитячі', 'МагДитячі'), ('МагГосподарські', 'МагГосподарські'), ('МагОдягТаВзуття', 'МагОдягТаВзуття'), ('МагВетиринарні', 'МагВетиринарні'), ('МагПосуд', 'МагПосуд'), ('ТелефониОргтехніка', 'ТелефониОргтехніка'), ('МагКвіти', 'МагКвіти'), ('ГосподарськіМагазини', 'ГосподарськіМагазини'), ('Канцелярія', 'Канцелярія'), ('Клініки', 'Клініки'), ('СалониКраси', 'СалониКраси'), ('СпортивніЗалиФітнес', 'СпортивніЗалиФітнес'), ('ШколиІступенів', 'ШколиІступенів'), ('ШколиІІступенів', 'ШколиІІступенів'), ('ШколиІІІступенів', 'ШколиІІІступенів'), ('Садочки', 'Садочки'), ('ПозашкільнаОсвіта', 'ПозашкільнаОсвіта'), ('ЦКіДи', 'ЦКіДи'), ('МузеїСадиби', 'МузеїСадиби'), ('Бібліотеки', 'Бібліотеки'), ('Туризм', 'Туризм'), ('міськаЛікарня', 'міськаЛікарня'), ('СімейнаМедицина', 'СімейнаМедицина'), ('Ветеринарія', 'Ветеринарія'), ('Аптеки', 'Аптеки'), ('Стоматології', 'Стоматології'), ('Лабораторії', 'Лабораторії'), ('ГромадськіОбєднання', 'ГромадськіОбєднання'), ('Церкви', 'Церкви'), ('Інші', 'Інші'), ('ЕкстреніСлужби', 'ЕкстреніСлужби'), ('ЗвязокТранспорт', 'ЗвязокТранспорт'), ('КомунальніСлужби', 'КомунальніСлужби'), ('ДержавніУстанови', 'ДержавніУстанови'), ('ІнтернетПровайдери', 'ІнтернетПровайдери'), ('ПоліграфіяДизайн', 'ПоліграфіяДизайн')], max_length=300, verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='botdatabase',
            name='coordinates',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Кординати'),
        ),
        migrations.AlterField(
            model_name='botdatabase',
            name='tel',
            field=models.CharField(blank=True, max_length=100, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='botdatabase',
            name='work_schedule',
            field=models.CharField(blank=True, max_length=100, verbose_name='Робочий графік'),
        ),
    ]
