# Generated by Django 4.2.1 on 2024-02-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminkaBot', '0005_rename_faсebookurl_botdatabase_facebookurl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botdatabase',
            name='isPublished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='botdatabase',
            name='Photo',
            field=models.ImageField(blank=True, default='', upload_to='photo/', verbose_name='Фото'),
        ),
    ]
